---
version: '3'

services:
  airbyte-tools:
    image: entechlog/airbyte-tools${AIRBYTE_TOOLS_VERSION_TAG}
    container_name: airbyte-tools
    build: ./docker/
    command: 
      - bash 
      - -c 
      - |
        echo "Launching airbyte-tools"
        sleep infinity
    restart: unless-stopped
    volumes:
      - type: bind
        source: /C
        target: /C
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - TZ=Etc/GMT
      - DOCKER_HOST=unix:///var/run/docker.sock
